### ISSUE TITLE
Errors when deploying in openshift

### ISSUE THREAD

**Issue by ccoldwell** [bcgov/MyGovBC-notification-server#5]
POD output:

Environment: 
	DEV_MODE=false
	NODE_ENV=production
	DEBUG_PORT=5858
Launching via npm...
npm info it worked if it ends with ok
npm info using npm@2.15.1
npm info using node@v4.4.2
npm info prestart notification@1.0.0
npm info start notification@1.0.0

> notification@1.0.0 start /opt/app-root/src
> node .

source dev db attributes
/opt/app-root/src/node_modules/loopback-boot/lib/config-loader.js:184
      throw new Error(g.f('Cannot apply %s: %s', fileName, err));
      ^

Error: Cannot apply /opt/app-root/src/server/middleware.production.json: The middleware "loopback#errorHandler" in phase "final:after"is not defined in the main config.
    at mergeMiddlewareConfig (/opt/app-root/src/node_modules/loopback-boot/lib/config-loader.js:184:13)
    at mergeConfigurations (/opt/app-root/src/node_modules/loopback-boot/lib/config-loader.js:149:5)
    at loadNamed (/opt/app-root/src/node_modules/loopback-boot/lib/config-loader.js:82:16)
    at Object.ConfigLoader.loadMiddleware (/opt/app-root/src/node_modules/loopback-boot/lib/config-loader.js:52:10)
    at compile (/opt/app-root/src/node_modules/loopback-boot/lib/compiler.js:73:18)
    at bootLoopBackApp (/opt/app-root/src/node_modules/loopback-boot/index.js:153:22)
    at Object.<anonymous> (/opt/app-root/src/server/server.js:34:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

npm info notification@1.0.0 Failed to exec start script
npm ERR! Linux 3.10.0-514.10.2.el7.x86_64
npm ERR! argv "/opt/rh/rh-nodejs4/root/usr/bin/node" "/opt/rh/rh-nodejs4/root/usr/bin/npm" "run" "-d" "start"
npm ERR! node v4.4.2
npm ERR! npm  v2.15.1
npm ERR! code ELIFECYCLE
npm ERR! notification@1.0.0 start: `node .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the notification@1.0.0 start script 'node .'.
npm ERR! This is most likely a problem with the notification package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs notification
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls notification
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /opt/app-root/src/npm-debug.log

**Comment by ccoldwell** [comment]
Thanks!
